services:
  # Frontend (React/Vite) - Static Site
  - type: web
    name: scottsdale-handyman-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend (Flask API) - Web Service
  - type: web
    name: scottsdale-handyman-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Add these in Render Dashboard Environment Variables:
      # FLASK_SECRET_KEY=C2kkKCnTHJXDHwTzhdFX3NC2rUNAx9jdn1ldXlqTmYA
      # MAIL_PASSWORD=nfsx nosf sfbp ckmp
      # STRIPE_PUBLISHABLE_KEY_TEST=pk_test_...
      # STRIPE_SECRET_KEY_TEST=sk_test_...
      # ENVIRONMENT=development
