services:
  # Customer Website (React/Vite) - Static Site
  - type: web
    name: scottsdale-handyman-website
    env: static
    rootDir: apps/website
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://scottsdale-handyman-api.onrender.com
      - key: VITE_PRO_PORTAL_URL
        value: https://scottsdale-handyman-pro-portal.onrender.com

  # Pro Portal (React/Vite) - Static Site
  - type: web
    name: scottsdale-handyman-pro-portal
    env: static
    rootDir: apps/pro-portal
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://scottsdale-handyman-api.onrender.com

  # API Backend (Flask) - Web Service
  - type: web
    name: scottsdale-handyman-api
    env: python
    rootDir: apps/api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Add these in Render Dashboard Environment Variables:
      # FLASK_SECRET_KEY=C2kkKCnTHJXDHwTzhdFX3NC2rUNAx9jdn1ldXlqTmYA
      # MAIL_PASSWORD=nfsx nosf sfbp ckmp
      # STRIPE_PUBLISHABLE_KEY_TEST=pk_test_...
      # STRIPE_SECRET_KEY_TEST=sk_test_...
      # GOOGLE_API_KEY=AIzaSyAUjw9Yk4sYC09AAADP6Gr07qwUEZyKHZ0
      # ENVIRONMENT=production
      # CORS_ORIGINS=https://scottsdale-handyman-website.onrender.com,https://scottsdale-handyman-pro-portal.onrender.com
